name: idp_chat
description: A new Flutter project.

publish_to:

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^2.13.1
  firebase_auth: ^4.6.2
  cloud_firestore: ^4.8.0
  firebase_database: ^10.2.2
  google_sign_in: ^6.1.4
  flutter_facebook_auth: ^5.0.0

  flutter_bloc: ^8.0.1

  freezed_annotation: ^2.2.0
  json_annotation: ^4.4.0

  flutter_svg: ^1.1.6

  either_dart:
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^2.0.3+1
  build_runner: ^2.1.8
  json_serializable: ^6.1.5

flutter:
  assets:
    - images/
  uses-material-design: true
